import sys
import json
import argparse
import base64
import os
from io import BytesIO
try:
    from PIL import Image, ImageDraw, ImageFont, ImageEnhance
except ImportError:
    print(json.dumps({"error": "Pillow library is not installed. Please install it using 'pip install Pillow'"}))
    sys.exit(1)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--image_b64', type=str, default='', help='Base64 encoded image from Gemini')
    parser.add_argument('--text', type=str, default='', help='Text generated by Local AI')
    args = parser.parse_args()

    # Load image from base64 or create a beautiful gradient fallback
    img = None
    if args.image_b64 and not args.image_b64.startswith("YOUR_") and len(args.image_b64) > 100:
        try:
            image_data = base64.b64decode(args.image_b64)
            img = Image.open(BytesIO(image_data))
        except Exception as e:
            pass
            
    if img is None:
        # Create a beautiful premium dark gradient (Deep Purple/Indigo to Midnight Black)
        gradient = Image.new('RGB', (1, 2))
        gradient.putpixel((0, 0), (25, 20, 52)) # Deep Indigo
        gradient.putpixel((0, 1), (6, 2, 15))   # Midnight Black
        try:
            resample_filter = Image.Resampling.BILINEAR
        except AttributeError:
            resample_filter = Image.BILINEAR
        img = gradient.resize((1080, 1920), resample_filter)

    # Resize to TikTok aspect ratio (9:16) -> 1080x1920
    img = img.resize((1080, 1920))

    # Darken the background by 30%
    enhancer = ImageEnhance.Brightness(img)
    img = enhancer.enhance(0.7)

    # Parse the text into 3 slides
    full_text = args.text
    pages = {"1": "", "2": "", "3": ""}
    
    current_page = None
    for line in full_text.split('\n'):
        if 'หน้า 1' in line:
            current_page = "1"
        elif 'หน้า 2' in line:
            current_page = "2"
        elif 'หน้า 3' in line:
            current_page = "3"
        elif current_page:
            pages[current_page] += line + '\n'

    # Try to load a font (adjust path if needed in your n8n container)
    try:
        font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
        font = ImageFont.truetype(font_path, 60)
    except IOError:
        font = ImageFont.load_default()

    output_paths = []
    
    # Process each slide
    for p_num, p_text in pages.items():
        if not p_text.strip():
            p_text = f"Slide {p_num}\n(No text generated)"
            
        slide_img = img.copy()
        draw = ImageDraw.Draw(slide_img)
        
        # Draw text (simple placement at the center/top)
        text_color = (255, 255, 255)
        
        # Basic multiline text rendering
        y_text = 600
        for line in p_text.strip().split('\n'):
            draw.text((100, y_text), line, fill=text_color, font=font)
            y_text += 80 # line spacing
            
        out_path = f"/data/tiktok-flow/tiktok_slide_{p_num}.jpg"
        slide_img.save(out_path)
        output_paths.append(out_path)

    # Print output as JSON for n8n to parse
    print(json.dumps({
        "success": True,
        "images": output_paths,
        "message": "Images generated successfully!"
    }))

if __name__ == "__main__":
    main()
